### ISSUE TITLE
(greengrass-cli): add option to interact with pub/sub topics

### ISSUE THREAD

**Issue by massi-ang** [aws-greengrass/aws-greengrass-cli#155]
**Feature Description**
Greengrass-cli should have an option to monitor pub/sub topics and be able to interact with them, similiar to `ros topic` (from ROS an ROS2)

**Use Case**
When developing applications on Greengrass it could be useful to be able to manually interact with the pub/sub

**Proposed Solution**
add subcommands such as
`greengrass-cli topic watch --topic --filter`
`greengrass-cli topic publish --topic --json-message --binary-message`

**Other**
Add detailed explanation, stacktraces, related issues, links for us to have context, etc

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

**Comment by junfuchen99** [comment]
Hello @massi-ang,

Thank you for your feature request. This is currently on our list of improvements for CLI, and we will update here once we have an ETA.

**Comment by MikeDombo** [comment]
Yes, it will do both. It isn't released yet, it will go out whenever 2.10 is released.

**Comment by gearoid-moore** [comment]
This is a major help for our team, to the point where we would like to try and deploy the main branch via a custom component, or via overwriting the local artefacts. 

Could you provide any instruction on how to achieve this ? Could be hacky ( local artifact overwrite ) , or better ( build via recipe file ourselves ) 



Ive run a maven build , and replaced the jar and cli zip files in the ‘artifacts’ dirs on the local Greengrass device we are using. 

Ive been able to run the commands in the example above, but I get unauthorised errors

**Comment by MikeDombo** [comment]
This change requires changes to both the CLI client and the CLI server (plugin to Nucleus). Make sure you do not have the CLI installed as a plugin first, then you can build the CLI and then drop the CliServer.jar file into /greengrass/v2/plugins/trusted and restart Greengrass. Greengrass will then load the plugin from there.

**Comment by gearoid-moore** [comment]
The hacky local copy worked a treat, thanks for the prompt reply. 

Developing components that depend on other components is a source of friction for us, and being able to emulate the behaviour of a dependent component without fully deploying it makes our life a lot easier.
